export enum ApplicationState {
  // ! MISSING INTERNAL APPROVAL AND DECLINES
  DRAFT = "DRAFT", // Normal save without submitting
  SUBMITTED = "SUBMITTED", // Application submitted to approver
  APPROVED = "APPROVED", // Approved by approver
  DECLINED = "DECLINED", // Declined by approver
  FINANCED = "FINANCED", // Liquid bridge paid money to the trust account
  PAID = "PAID" // Client paid back liquid bridge
}
export enum EmailType {
  // Emails to us
  APPLICATION_APPROVED_TO_US = "APPLICATION_APPROVED_TO_US",
  // Approver emails
  APPLICATION_APPROVED_TO_APPROVER = "APPLICATION_APPROVED_TO_APPROVER",
  APPLICATION_SUBMITTED_TO_APPROVER = "APPLICATION_SUBMITTED_TO_APPROVER",
  APPLICATION_DECLINED_TO_APPROVER = "APPLICATION_DECLINED_TO_APPROVER",
  // Client emails
  APPLICATION_SUBMITTED_TO_CLIENT = "APPLICATION_SUBMITTED_TO_CLIENT",
  APPLICATION_FINANCED_TO_CLIENT = "APPLICATION_FINANCED_TO_CLIENT",
  APPLICATION_DECLINED_TO_CLIENT = "APPLICATION_DECLINED_TO_CLIENT",
  USER_CREATED = "USER_CREATED",
  QUOTE_GENERATED = "QUOTE_GENERATED"
}

export enum SettlementStatementStatus {
  REQUESTED = "REQUESTED",
  SENT = "SENT",
  SETTLED = "SETTLED"
}
